"use client";
import { useRef, useState } from "react";

export function PaidVoteForm({ eventId, categoryId, nomineeId, nomineeName, unitPriceMinor, defaultEmail }: { eventId:string; categoryId:string; nomineeId:string; nomineeName:string; unitPriceMinor:number; defaultEmail?:string|null }) {
  const attempt=useRef<{details:string;key:string}|null>(null);
  const [quantity,setQuantity]=useState(1); const [email,setEmail]=useState(defaultEmail ?? ""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function submit(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { const details=JSON.stringify({eventId,categoryId,nomineeId,quantity,email}); if(attempt.current?.details!==details)attempt.current={details,key:crypto.randomUUID()}; const r=await fetch("/api/payments/paystack/vote",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({eventId,categoryId,nomineeId,quantity,email,requestKey:attempt.current.key})}); const d=await r.json(); if(!r.ok) throw new Error(d.error||"Unable to start payment"); window.location.assign(d.authorization_url); } catch (err) { setError(err instanceof Error?err.message:"Unable to start payment"); setBusy(false); } }
  return <form className="space-y-3 [&_label]:block [&_label]:text-sm [&_label]:font-medium [&_input]:mt-1 [&_input]:min-h-11 [&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-stone-300 [&_input]:bg-white [&_input]:px-3 [&_input]:text-base" onSubmit={submit}><label>Votes<input type="number" min={1} max={10000} value={quantity} onChange={e=>setQuantity(Math.max(1,Math.min(10000,Number(e.target.value)||1)))} /></label><label>Email for receipt<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" /></label><button type="submit" className="inline-flex items-center justify-center gap-2 rounded-xl border border-emerald-900 bg-emerald-900 px-5 py-3 text-sm font-semibold text-white shadow-xs hover:bg-emerald-800 min-h-11 cursor-pointer focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-700 disabled:cursor-not-allowed disabled:opacity-50" disabled={busy}>{busy?"Opening Paystack…":`Pay GHS ${((unitPriceMinor*quantity)/100).toFixed(2)} for ${nomineeName}`}</button>{error&&<p className="form-error" role="alert">{error}</p>}</form>;
}

