import Link from "next/link";
import { SiteHeader } from "@/components/site-header";
import { publicMetadata } from "@/lib/seo/metadata";

export const metadata = publicMetadata("Online voting pricing and organizer costs", "Understand free and paid voting on VotecastHub GH, the 10% inclusive fee on paid collections, SMS credits and organizer payment setup.", "/pricing");
export default function PricingPage() {
  return <main><SiteHeader /><article className="mx-auto max-w-4xl px-4 py-12 sm:px-6">
    <p className="text-xs font-semibold uppercase tracking-widest text-emerald-800">Pricing explained</p><h1 className="mt-3 text-3xl font-semibold text-stone-900 sm:text-5xl">Know the costs before you publish.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-stone-600">Choose whether voters participate for free or pay the price you set for each vote. The event’s voting page shows the selected format.</p>
    <div className="mt-8 grid gap-5 md:grid-cols-2"><section className="rounded-2xl border border-stone-200 p-6"><h2 className="text-xl font-semibold text-stone-900">Free voting</h2><p className="mt-3 text-3xl font-semibold text-emerald-900">GHS 0 <span className="text-base font-normal text-stone-600">per vote for voters</span></p><p className="mt-4 leading-7 text-stone-700">Voters do not pay to record a free vote. Organizers choose a verification method and voting limit. Phone verification requires organizer-funded SMS credits; check the current top-up amount and balance in your workspace.</p><Link href="/guides/voter-verification-and-voting-limits" className="mt-4 inline-flex min-h-11 items-center font-semibold text-emerald-800 underline">Compare verification methods</Link></section>
    <section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6"><h2 className="text-xl font-semibold text-stone-900">Paid voting</h2><p className="mt-3 text-3xl font-semibold text-emerald-900">10% <span className="text-base font-normal text-stone-600">inclusive collection fee</span></p><p className="mt-4 leading-7 text-stone-700">You set the price per vote in Ghana cedis. The platform’s 10% share includes payment-provider processing costs; those costs are not deducted a second time from the organizer’s share. Before refunds or adjustments, the organizer’s share is 90% of the collected amount.</p><p className="mt-3 leading-7 text-stone-700">For example, GHS 100 in confirmed paid collections gives a GHS 10 inclusive fee and a GHS 90 organizer share, before refunds or adjustments.</p></section></div>
    <section className="mt-9"><h2 className="text-xl font-semibold text-stone-900">Payment setup and records</h2><p className="mt-3 leading-7 text-stone-700">A paid event requires a verified organizer Paystack account before publication. Your workspace shows confirmed payments, refunds, fees and organizer earnings. Settlement timing depends on the payment provider and your account status.</p></section>
    <section className="mt-9"><h2 className="text-xl font-semibold text-stone-900">Before inviting voters</h2><p className="mt-3 leading-7 text-stone-700">Check the price, dates and voting instructions, then submit your event for platform review. Publication approval is required before the event becomes publicly available.</p></section>
    <div className="mt-9 flex flex-wrap gap-4"><Link href="/sign-up" className="inline-flex min-h-11 items-center rounded-xl bg-emerald-900 px-5 font-semibold text-white">Get started</Link><Link href="/guides" className="inline-flex min-h-11 items-center px-3 font-semibold text-emerald-800">Read organizer guides →</Link></div><p className="mt-8 text-sm leading-6 text-stone-600">Questions about your event’s costs? Contact <a className="text-emerald-800 underline" href="mailto:info@votecasthub.com">info@votecasthub.com</a>. See the <Link className="text-emerald-800 underline" href="/terms">terms</Link> for participation and payment conditions.</p>
  </article></main>;
}
