import type { Metadata } from "next";
import Link from "next/link";
import { SiteHeader } from "@/components/site-header";

export const metadata: Metadata = { title: "Terms & Conditions", description: "Terms for organizers and participants using VotecastHub GH." };

export default function TermsPage() {
  return <main className="public-page"><SiteHeader /><article className="legal-page mx-auto w-full motion-safe:animate-[page-in_.35s_ease-out_both]">
    <p className="eyebrow">TERMS &amp; CONDITIONS</p><h1 className="text-balance">Clear expectations for using VotecastHub.</h1>
    <p className="legal-lead">These terms cover access to VotecastHub GH, organization workspaces, public events, and participation features.</p><p className="legal-updated">Effective date: 2 October 2026 · Last reviewed: 2 October 2026</p>
    <div className="legal-callout"><strong>Operator</strong><p>VotecastHub GH is the working product name. The operator’s contact email is <a href="mailto:josephmarfo1998@gmail.com">josephmarfo1998@gmail.com</a>; location: Tanoso, Kumasi, Ghana. The operator’s registered legal name has not yet been supplied.</p></div>
    <section><h2>1. Accepting these terms</h2><p>By creating an account or using organizer features, you agree to these terms and our <Link href="/privacy">Privacy Policy</Link>. If you use the service for an organization, you confirm that you are authorized to act for it.</p></section>
    <section><h2>2. Accounts and access</h2><p>Provide accurate account information, keep your sign-in credentials secure, and promptly report suspected unauthorized access. You are responsible for activity under your account. Organization owners manage team access and should remove access when it is no longer needed.</p></section>
    <section><h2>3. Organizer responsibilities</h2><p>Organizers are responsible for event rules, eligibility, nominee permissions, image and content rights, lawful collection of participant information, and communicating event decisions. Do not upload content that is unlawful, misleading, abusive, or violates another person’s rights.</p></section>
    <section><h2>4. Events and voting</h2><p>Event availability, voting methods, eligibility limits, and result visibility are determined by the event’s published configuration. The service may not enable voting, payments, or USSD for every event. Do not represent an event as accepting votes or payments unless the page explicitly provides that feature. We may suspend content or access to protect users or the service.</p></section>
    <section><h2>5. Acceptable use</h2><p>Do not attempt to bypass security or voting limits, interfere with the service, submit malicious code, impersonate another person, or use the service for fraud or unlawful activity. We may investigate suspected misuse and restrict access where reasonably necessary.</p></section>
    <section><h2>6. Content and service availability</h2><p>You retain rights to content you submit. You grant us permission to host, process, and display that content as needed to operate the service and the event. We may update or interrupt features and do not guarantee uninterrupted availability or error-free results. Organizers should keep their own important records.</p></section>
    <section><h2>7. Suspension and termination</h2><p>You may stop using your account. Contact us for account closure or data requests. We may suspend or terminate access for violations, security risks, legal requirements, or service discontinuation. Some records may be retained when required for legitimate operational or legal purposes, as described in the Privacy Policy.</p></section>
    <section><h2>8. Disclaimers and liability</h2><p>To the extent permitted by applicable law, the service is provided without warranties beyond those that cannot lawfully be excluded. Nothing in these terms excludes liability that cannot legally be excluded or limits consumer rights that apply under Ghanaian law.</p></section>
    <section><h2>9. Changes and governing law</h2><p>We may update these terms as the service develops. Continued use after a published update means you accept the revised terms where the law permits. These terms are governed by the laws of Ghana, subject to applicable mandatory consumer protections.</p></section>
    <section><h2>10. Contact</h2><p>Questions about these terms: <a href="mailto:josephmarfo1998@gmail.com">josephmarfo1998@gmail.com</a>.</p></section>
    <p className="legal-note">This is an operator draft, not a legal review. Confirm the contracting legal entity, service promises, dispute process, payment/refund terms, organizer and voter eligibility, and liability language with Ghana-qualified counsel before launch.</p>
  </article><footer className="site-footer"><Link className="brand footer-brand" href="/"><span className="brand-mark">V</span><span>VotecastHub<span className="brand-accent"> GH</span></span></Link><nav aria-label="Legal and company links"><Link href="/about">About</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></nav><span>© {new Date().getFullYear()} VotecastHub GH</span></footer></main>;
}
