import type { Metadata } from "next";
import Link from "next/link";
import { CookieSettingsLink } from "@/components/cookie-consent";
import { SiteHeader } from "@/components/site-header";

export const metadata: Metadata = { title: "Privacy Policy", description: "How VotecastHub GH handles account, organization, event, and preference information." };

export default function PrivacyPage() {
  return <main className="public-page"><SiteHeader /><article className="legal-page mx-auto w-full motion-safe:animate-[page-in_.35s_ease-out_both]">
    <p className="eyebrow">PRIVACY POLICY</p><h1 className="text-balance">Your information, handled with care.</h1><p className="legal-lead">This policy describes information VotecastHub GH may handle when you browse the site, create an account, manage an organization, or take part in an event.</p>
    <p className="legal-updated">Effective date: 2 October 2026 · Last reviewed: 2 October 2026</p>
    <div className="legal-callout"><strong>Operator details</strong><p>VotecastHub GH is the product and working name supplied by its operator. The operator has provided the contact email <a href="mailto:josephmarfo1998@gmail.com">josephmarfo1998@gmail.com</a> and location Tanoso, Kumasi, Ghana. A registered legal entity name and street address have not been provided.</p></div>
    <section><h2>Information involved</h2><ul><li><strong>Account and security:</strong> display name, email address, and—if you choose phone sign-in—your Ghana phone number and verification status. Supabase manages authentication and session information needed to sign in and protect accounts.</li><li><strong>Organization and event content:</strong> organization and team details, event configuration, categories, nominee names, biographies, and images uploaded by authorized organizers.</li><li><strong>Voting:</strong> for free voting, a verified account’s vote records are associated with the event, category, nominee, and authenticated voter account to enforce the event’s limits and prevent duplicate requests. Other participation information depends on which feature is enabled for the event.</li><li><strong>Technical information:</strong> basic request and device information processed by the hosting and infrastructure services that deliver and secure the site.</li><li><strong>Preferences:</strong> your optional analytics and marketing choices. The current preference controls are stored in this browser; essential authentication/session storage is separate.</li></ul></section>
    <section><h2>How we use information</h2><p>We use information to provide account access, operate organization workspaces, display events and nominee profiles, protect the service, respond to support requests, and meet applicable legal obligations. Optional analytics or advertising technologies should only be activated after you choose the relevant category in Cookie settings.</p></section>
    <section><h2>Phone verification and voting integrity</h2><p>When you vote in a free event, we process your phone number through Supabase Auth to send and verify a one-time code. The number and verification status are used to create a secure voter identity, apply the event’s voting limits, prevent duplicate or automated voting, investigate suspicious activity, and protect the integrity of results. Your phone number is not displayed publicly and is not used for marketing without a separate lawful basis.</p><p>Supabase Auth retains one account record for each verified phone number. We retain that record and the minimum vote and security records needed while an event is active, while results or disputes may reasonably be challenged, and for applicable legal or fraud-prevention requirements. When those purposes end, records are deleted or irreversibly de-identified according to our retention procedures. You may contact us to request access or deletion; deletion may be limited where it would undermine a live vote, an audit trail, or a legal obligation.</p></section>
    <section><h2>Cookies and similar storage</h2><p>Essential session storage is used for sign-in and security. The preference control stores your choices in this browser’s local storage. Analytics and marketing technologies are optional and currently remain disabled until a provider is configured and you grant the corresponding permission. You can revisit your choices at any time.</p><CookieSettingsLink /></section>
    <section><h2>Service providers and transfers</h2><p>VotecastHub GH uses Supabase for database and authentication services and Vercel for hosting and delivery. Supabase may also route phone verification messages through its configured authentication provider. These providers process information to provide their services under their own terms. Their infrastructure may process data in locations outside Ghana. The operator should confirm configured regions, contracts, and applicable transfer safeguards before public launch. Payment provider processing should be added to this notice before any payment option is enabled.</p></section>
    <section><h2>Retention and security</h2><p>Information is retained only for the purposes described above: account and phone-verification records while the account or an integrity review requires them, event and vote records while results and disputes may reasonably be challenged, and financial or audit records for the period required by law. We periodically review records for deletion or irreversible de-identification. We use access controls and service safeguards, but no internet service can guarantee absolute security.</p></section>
    <section><h2>Your choices and rights</h2><p>You may update account information, manage optional tracking preferences, and contact us to request access, correction, deletion, or to raise a privacy concern. We will verify requests and respond subject to applicable law, including Ghana’s Data Protection Act, 2012 (Act 843). You may also contact the <a href="https://dataprotection.org.gh/" rel="noreferrer">Ghana Data Protection Commission</a> for guidance or complaints.</p></section>
    <section><h2>Children</h2><p>The service is designed for organizers and event participants. Organizers are responsible for ensuring they have an appropriate basis and any required permissions before submitting information or images about nominees, especially children.</p></section>
    <section><h2>Changes and contact</h2><p>We may revise this policy when the service changes. Material updates will be reflected here with a new review date. For privacy questions, email <a href="mailto:josephmarfo1998@gmail.com">josephmarfo1998@gmail.com</a>.</p></section>
    <p className="legal-note">This page is an operational draft based on information currently provided by the operator. Confirm the legal controller identity, data retention periods, enabled voting/payment providers, hosting regions, and applicable Ghana Data Protection Commission registration and compliance requirements before treating it as final.</p>
  </article><footer className="site-footer"><Link className="brand footer-brand" href="/"><span className="brand-mark">V</span><span>VotecastHub<span className="brand-accent"> GH</span></span></Link><nav aria-label="Legal and company links"><Link href="/about">About</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></nav><span>© {new Date().getFullYear()} VotecastHub GH</span></footer></main>;
}
