import { NextResponse } from "next/server";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { paystackSecret } from "@/lib/payments/paystack";
import { resolveSettlement } from "@/lib/payments/settlement";
export const runtime = "nodejs";
const input = z.object({ organizationId:z.string().uuid(), type:z.enum(["ghipss","mobile_money"]), confirmedAccountName:z.string().min(1).max(200), businessName:z.string().trim().min(2).max(160), bankCode:z.string().trim().min(2).max(12), accountNumber:z.string().min(6).max(24), contactName:z.string().trim().min(2).max(120), contactPhone:z.string().trim().min(7).max(24) });
export async function POST(request:Request) { try { const body=input.safeParse(await request.json()); if(!body.success) return NextResponse.json({error:"Check the payment account details."},{status:400}); const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user?.email) return NextResponse.json({error:"Sign in required"},{status:401}); const {data:member}=await supabase.from("organization_members").select("role").eq("organization_id",body.data.organizationId).eq("user_id",user.id).maybeSingle(); if(!member||!['owner','admin'].includes(member.role)) return NextResponse.json({error:"Organization access denied"},{status:403}); const p=body.data; const resolved=await resolveSettlement(p.type,p.bankCode,p.accountNumber); if(resolved.accountName!==p.confirmedAccountName) return NextResponse.json({error:"Account name changed. Verify the account again."},{status:409}); const response=await fetch("https://api.paystack.co/subaccount",{method:"POST",headers:{Authorization:`Bearer ${paystackSecret()}`,"Content-Type":"application/json"},body:JSON.stringify({business_name:p.businessName,bank_code:p.bankCode,account_number:resolved.accountNumber,percentage_charge:10,primary_contact_name:p.contactName,primary_contact_email:user.email,primary_contact_phone:p.contactPhone,metadata:JSON.stringify({organization_id:p.organizationId})})}); const result=await response.json(); if(!response.ok||!result.status) return NextResponse.json({error:"Paystack could not create this payment account."},{status:502}); const account=result.data; const url=process.env.NEXT_PUBLIC_SUPABASE_URL, key=process.env.SUPABASE_SECRET_KEY; if(!url||!key) return NextResponse.json({error:"Server payment configuration is incomplete."},{status:503}); const saved=await fetch(`${url}/rest/v1/organization_paystack_accounts`,{method:"POST",headers:{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json","Prefer":"return=minimal"},body:JSON.stringify({organization_id:p.organizationId,subaccount_code:account.subaccount_code,business_name:p.businessName,settlement_bank:account.settlement_bank,account_last4:resolved.accountNumber.slice(-4),status:account.is_verified?'active':'pending',paystack_verified:Boolean(account.is_verified),percentage_charge:10})}); if(!saved.ok) return NextResponse.json({error:"Payment account was created but could not be saved."},{status:503}); return NextResponse.json({status:account.is_verified?'active':'pending'}); } catch { return NextResponse.json({error:"Payment account service unavailable."},{status:503}); } }

