alter table public.organizations add column if not exists moderation_status text not null default 'active' check(moderation_status in ('active','restricted','suspended'));
create table if not exists public.moderation_flags(id uuid primary key default gen_random_uuid(),organization_id uuid references public.organizations(id) on delete cascade,event_id uuid references public.events(id) on delete cascade,user_id uuid references auth.users(id) on delete set null,kind text not null check(char_length(kind) between 2 and 60),severity smallint not null default 1 check(severity between 1 and 5),details text not null check(char_length(details)<=1000),status text not null default 'open' check(status in ('open','reviewed','dismissed')),created_at timestamptz not null default now(),reviewed_at timestamptz,reviewed_by uuid references auth.users(id));
alter table public.moderation_flags enable row level security;
revoke all on public.moderation_flags from public,anon,authenticated; grant all on public.moderation_flags to service_role;
create or replace function public.get_admin_moderation_flags() returns table(id uuid,organization_id uuid,event_id uuid,kind text,severity smallint,details text,status text,created_at timestamptz) language sql stable security definer set search_path='' as $$ select f.id,f.organization_id,f.event_id,f.kind,f.severity,f.details,f.status,f.created_at from public.moderation_flags f where exists(select 1 from public.platform_admins a where a.user_id=auth.uid() and a.is_active) and f.status='open' order by f.severity desc,f.created_at asc limit 200; $$;
revoke all on function public.get_admin_moderation_flags() from public,anon; grant execute on function public.get_admin_moderation_flags() to authenticated;
create or replace function public.admin_set_organization_moderation(p_org uuid,p_status text,p_note text) returns void language plpgsql security definer set search_path='' as $$ declare uid uuid:=auth.uid(); begin if not exists(select 1 from public.platform_admins where user_id=uid and is_active) then raise exception 'Platform admin access required'; end if; if p_status not in ('active','restricted','suspended') then raise exception 'Invalid moderation status'; end if; update public.organizations set moderation_status=p_status,updated_at=now() where id=p_org; insert into public.admin_audit_log(admin_user_id,action,target_type,target_id,note) values(uid,'set_organization_moderation','organization',p_org,p_status||': '||coalesce(p_note,'')); end $$;
revoke all on function public.admin_set_organization_moderation(uuid,text,text) from public,anon,authenticated; grant execute on function public.admin_set_organization_moderation(uuid,text,text) to authenticated;
create or replace function public.get_admin_organizations() returns table(id uuid,name text,moderation_status text,event_count bigint,paystack_status text,paystack_verified boolean) language sql stable security definer set search_path='' as $$ select o.id,o.name,o.moderation_status,count(e.id),coalesce(a.status,'not_connected'),coalesce(a.paystack_verified,false) from public.organizations o left join public.events e on e.organization_id=o.id left join public.organization_paystack_accounts a on a.organization_id=o.id where exists(select 1 from public.platform_admins p where p.user_id=auth.uid() and p.is_active) group by o.id,o.name,o.moderation_status,a.status,a.paystack_verified order by o.created_at desc limit 500; $$;
revoke all on function public.get_admin_organizations() from public,anon; grant execute on function public.get_admin_organizations() to authenticated;
create or replace function public.get_admin_organization_profile(p_org uuid) returns table(id uuid,name text,moderation_status text,event_id uuid,event_name text,event_status text,paystack_status text,paystack_verified boolean) language sql stable security definer set search_path='' as $$ select o.id,o.name,o.moderation_status,e.id,e.name,e.status,coalesce(a.status,'not_connected'),coalesce(a.paystack_verified,false) from public.organizations o left join public.events e on e.organization_id=o.id left join public.organization_paystack_accounts a on a.organization_id=o.id where o.id=p_org and exists(select 1 from public.platform_admins p where p.user_id=auth.uid() and p.is_active) order by e.created_at desc; $$;
revoke all on function public.get_admin_organization_profile(uuid) from public,anon; grant execute on function public.get_admin_organization_profile(uuid) to authenticated;

create or replace function public.record_moderation_flag(p_organization_id uuid,p_event_id uuid,p_user_id uuid,p_kind text,p_severity smallint,p_details text) returns uuid language plpgsql security definer set search_path='' as $$ declare flag_id uuid; begin if current_user not in ('service_role','postgres') then raise exception 'Service role required'; end if; if p_severity not between 1 and 5 or char_length(btrim(p_details))<3 then raise exception 'Invalid moderation flag'; end if; insert into public.moderation_flags(organization_id,event_id,user_id,kind,severity,details) values(p_organization_id,p_event_id,p_user_id,p_kind,p_severity,p_details) returning id into flag_id; return flag_id; end $$;
revoke all on function public.record_moderation_flag(uuid,uuid,uuid,text,smallint,text) from public,anon,authenticated; grant execute on function public.record_moderation_flag(uuid,uuid,uuid,text,smallint,text) to service_role;
create or replace function public.admin_review_moderation_flag(p_flag_id uuid,p_status text) returns void language plpgsql security definer set search_path='' as $$ declare uid uuid:=auth.uid(); begin if not exists(select 1 from public.platform_admins where user_id=uid and is_active) then raise exception 'Platform admin access required'; end if; if p_status not in ('reviewed','dismissed') then raise exception 'Invalid review status'; end if; update public.moderation_flags set status=p_status,reviewed_at=now(),reviewed_by=uid where id=p_flag_id and status='open'; insert into public.admin_audit_log(admin_user_id,action,target_type,target_id,note) values(uid,'review_moderation_flag','moderation_flag',p_flag_id,p_status); end $$;
revoke all on function public.admin_review_moderation_flag(uuid,text) from public,anon,authenticated; grant execute on function public.admin_review_moderation_flag(uuid,text) to authenticated;
