create table if not exists public.event_access_codes(
 id uuid primary key default gen_random_uuid(), event_id uuid not null references public.events(id) on delete cascade,
 code_hash text not null unique, label text, max_redemptions integer not null default 1 check(max_redemptions between 1 and 100000), redemption_count integer not null default 0 check(redemption_count>=0), expires_at timestamptz, created_by uuid not null references auth.users(id), created_at timestamptz not null default now()
);
alter table public.events drop constraint if exists events_verification_method_check;
alter table public.events add constraint events_verification_method_check check (verification_method in ('phone','email','invite_code','captcha_limited'));
create or replace function public.set_event_verification_method(p_event_id uuid,p_method text) returns void language plpgsql security definer set search_path='' as $$ declare org_id uuid; status text; begin if p_method not in ('phone','email','invite_code') then raise exception 'Invalid verification method' using errcode='22023'; end if; select organization_id,status into org_id,status from public.events where id=p_event_id for update; if not found or not private.can_manage_org(org_id) then raise exception 'Organization access denied' using errcode='42501'; end if; if status<>'draft' then raise exception 'Verification method can only be changed while the event is a draft' using errcode='22023'; end if; update public.events set verification_method=p_method,updated_at=now() where id=p_event_id; end $$;
create table if not exists public.event_access_code_redemptions(
 id uuid primary key default gen_random_uuid(), access_code_id uuid not null references public.event_access_codes(id) on delete cascade, voter_user_id uuid not null references auth.users(id) on delete cascade, redeemed_at timestamptz not null default now(), unique(access_code_id,voter_user_id)
);
alter table public.event_access_codes enable row level security; alter table public.event_access_code_redemptions enable row level security;
revoke all on public.event_access_codes,public.event_access_code_redemptions from public,anon,authenticated;
grant select,insert,update,delete on public.event_access_codes to authenticated;
grant select on public.event_access_code_redemptions to authenticated;
create policy access_code_manage on public.event_access_codes for all to authenticated using(private.can_manage_org((select organization_id from public.events where id=event_id))) with check(private.can_manage_org((select organization_id from public.events where id=event_id)));
create policy access_code_redemption_read on public.event_access_code_redemptions for select to authenticated using(exists(select 1 from public.event_access_codes c join public.events e on e.id=c.event_id where c.id=access_code_id and private.can_manage_org(e.organization_id)) or voter_user_id=auth.uid());
create function public.redeem_event_access_code(p_event_id uuid,p_code_hash text) returns uuid language plpgsql security definer set search_path='' as $$ declare c public.event_access_codes; r uuid; uid uuid:=auth.uid(); begin if uid is null then raise exception 'Authentication required' using errcode='42501'; end if; select * into c from public.event_access_codes where event_id=p_event_id and code_hash=p_code_hash for update; if not found or (expires_at is not null and expires_at<=now()) then raise exception 'Access code is invalid or expired' using errcode='22023'; end if; if c.redemption_count>=c.max_redemptions then raise exception 'Access code has reached its limit' using errcode='22023'; end if; insert into public.event_access_code_redemptions(access_code_id,voter_user_id) values(c.id,uid) on conflict do nothing returning id into r; if r is null then raise exception 'This voter has already used the access code' using errcode='23505'; end if; update public.event_access_codes set redemption_count=redemption_count+1 where id=c.id; return r; end $$;
revoke all on function public.redeem_event_access_code(uuid,text) from public,anon; grant execute on function public.redeem_event_access_code(uuid,text) to authenticated;
